// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amuvuhvjlnqfjzgkhzih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtdXZ1aHZqbG5xZmp6Z2toemloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTE1MTYsImV4cCI6MjA1ODA4NzUxNn0.-_hp4U1siRhrBtuSic5qP6Zaw9UhQuTb_TtbjqqtOz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);